name = input("Enter your name: ")
age = int(input("Enter your age: "))
height = float(input("Enter your height in meters: "))
weight = float(input("Enter your weight in kilograms: "))
bmi = weight / (height ** 2)
age_next_year = age + 1
print()
print("============================")
print("      USER PROFILE      ")
print("============================")
print("Name:", name)
print("Age:", age)
print("Height:", height,"m")
print("Weight:", weight,"kg")
print("BMI:", round(bmi, 1))
print("Age next year:", age_next_year)
print("============================")