print("Hello world")
print("My name is Richmond")

print("welcome")
print("to")
print("python")
print("programming")

print("================================")
print("    MY PROFILE    ")
print("================================")
print("Name: Richmond")
print("Age:", 19)
print("country: Nigeria")
print("profession: Computer Science Student")
print("===============================")
